### ISSUE TITLE
fix: neither id nor url receives a prepended host

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-schema-org#9] opened 2022-12-27 00:05 UTC
### Describe the bug

Reading https://unhead-schema-org.harlanzw.com/guide/getting-started/how-it-works I'd expect an id and an url to receive a prepended host. Looking at the minimal reproduction's debug output though, I only see
```
      "publisher": {
        "name": "123",
        "url": "/test"
      },
      "test": {
        "@id": "#identity"
      }
```
and no `http://example.com`.

### Reproduction

https://stackblitz.com/edit/github-n9w3b7-itsa38?file=app.vue

### System Info

```Shell
see stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment] 2022-12-27 02:49
Amazing, thanks for the reproduction.

Both issues would point to the fact that the package only aims to provide automatic resolving for fields that Google recommends for Rich Results and it doesn't apply universal resolving. 

The `publisher` example is an interesting one, since you're providing input, it's ambiguous what schema type you're providing, as it could either be a Person or an Organisation, so it won't provide any resolving for you. The recommendation there would be:
- leave it blank and inherit the site identity
- use `definePerson` or `defineOrganisation`

Like wise to fully qualify the id with the prefixed URL, we need to know the node relation, as some nodes have a root id while others have a path id. This is normally mapped for known relations, but obviously test can't be known ahead of time.

Do you have a real-life example similar to the reproduction that could provide some more insight into fixes?

**Comment by dargmuesli** [comment] 2022-12-27 03:49
Sure, I've updated the reproduction to a slightly more concise use case: put simply, I want to reference a previously defined organization manually by using
```ts
publisher: {
      '@type': 'Organization',
      '@id': '#identity',
},
```
but as you can see using the same link as above there is still no host prepended.

Of course my use case is a further, but it boils down to being able to set an arbitrary publisher organization, e.g. simply the default, the only one existing.

**Closed** 2023-09-03 12:31 UTC
