### ISSUE TITLE
Client side reactivity updates

### ISSUE THREAD

**Issue by sumerokr** [harlan-zw/nuxt-schema-org#18] opened 2023-04-04 08:24 UTC
### Details

Hi there. First of all thanks for the package!

I have a question related to client side reactivity. [Documentation](https://unhead-schema-org.harlanzw.com/integrations/vue/reactivity) says:
> full reactivity is provided out of the box
> All values are reactive
> When using reactivity in CSR, any ref changes will trigger a request to update the DOM.

But I just can't make it work.
I have tried `ref`, `useState`, wrapping in `if (process.client)`, moving under `onMounted` hook. No results.
Please see a reproduction link and my comments in the code and template sections.

https://stackblitz.com/edit/github-rsbzrb?file=app.vue

**Update**
Above link doesn't work anymore (deleted by accident). See message below.

**Comment by harlan-zw** [comment] 2023-04-18 07:35
Hey! I'd be happy to investigate this but looks like the reproduction isn't available anymore.

**Comment by sumerokr** [comment] 2023-04-18 07:47
> Hey! I'd be happy to investigate this but looks like the reproduction isn't available anymore.

Oh, god. Looks like it was deleted by accident. I'll recreate it soon and paste a new link. Thanks for the catch.

**Comment by sumerokr** [comment] 2023-04-18 08:23
I created a super simple reproduction. Just a single app.vue file. One `ref` linked to `defineWebPage` name.
My expectation that the `<script type="application/ld+json" id="schema-org-graph">` will be updated according to this page: https://unhead-schema-org.harlanzw.com/integrations/vue/reactivity#reactive-composables, which says
> full reactivity is provided out of the box
> All values are reactive
> When using reactivity in CSR, **any ref changes will trigger a request to update the DOM**.

**Comment by sumerokr** [comment] 2023-04-18 09:09
@harlan-zw sorry, I forgot to add the link to the prev. message. Updated.

**Comment by Bastinck** [comment] 2023-05-15 09:20
I'm not sure why the check for SPA is there, I think the mode should always be 'all'. Here is my fix:

 ` return useHead({
    script: [
      {
        type: "application/ld+json",
        id: "schema-org-graph",
        key: "schema-org-graph",
        // @ts-expect-error runtime type
        nodes: () =>  input
      }
    ]
  });`

**Comment by harlan-zw** [comment] 2023-05-20 17:02
For some context, I was able to replicate the reactivity issue. I started looking into a fix but didn't get too far into it. 

My capacity for this package it currently pretty limited but I hope to get back on to this issue when time permists.

**Comment by harlan-zw** [comment] 2023-11-15 11:01
> Here is the link: [stackblitz.com/edit/nuxt-starter-za9gfg?file=app.vue](https://stackblitz.com/edit/nuxt-starter-za9gfg?file=app.vue)

Just tested this out with the latest version and it seems to be solve so I'll close this one off.

**Closed by harlan-zw** 2023-11-15 11:01 UTC
